services:
  arch-reflector:
    build: .
    container_name: arch-reflector
    environment:
      # If you want to run once and exit:
      # - ONE_SHOT=true
      # Otherwise, rely on cron:
      - ONE_SHOT=false
      - REFLECTOR_SCHEDULE=0 0 * * *
      # Without REFLECTOR_ARGS, defaults are used
      # - REFLECTOR_ARGS="--country France,Germany --latest 10 --protocol https --save /etc/pacman.d/mirrorlist"
    volumes:
      - mirrorlist:/etc/pacman.d
    restart: always

volumes:
  mirrorlist:
