services:
  arch-reflector:
    image: mschabhuettl/arch-reflector-docker:latest
    container_name: arch-reflector
    environment:
      # Update once and exit (ONE_SHOT=true) or run periodically (ONE_SHOT=false, default)
      - ONE_SHOT=false

      # Cron schedule for periodic updates (default: "0 * * * *", hourly)
      - REFLECTOR_SCHEDULE=0 * * * *

      # Reflector arguments (optional, defaults shown below)
      # Example: --save /etc/pacman.d/mirrorlist --country France,Germany --protocol https --latest 5
      # Uncomment to override defaults:
      # - REFLECTOR_ARGS=--save /etc/pacman.d/mirrorlist --country Austria --protocol https --latest 10

      # Timezone for the container (default: UTC)
      # Uncomment and adjust to your timezone:
      # - TZ=Europe/Vienna

      # Logging level: "quiet", "normal" (default), or "debug"
      - LOG_LEVEL=normal

    volumes:
      # Persist mirrorlist to ensure changes survive container restarts
      - mirrorlist:/etc/pacman.d

    restart: always

    healthcheck:
      # Verify container health with a 30s interval and 5s timeout
      test: ["CMD", "pgrep", "crond"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mirrorlist:
