name: Advanced Build, Test, and Push Docker CI/CD Workflow

on:
  push:
    branches:
      - main          # Trigger on pushes to main
      - "release/*"   # Trigger on release branches
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read   # Required to read repository contents
      packages: write  # Required for GitHub Container Registry (GHCR)

    strategy:
      matrix:
        architecture: [amd64]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run Security Tests
      - name: Run Security Tests
        run: |
          chmod +x tests/test_security.sh
          ./tests/test_security.sh

      # Step 3: Run Functionality Tests
      - name: Run Functionality Tests
        run: |
          chmod +x tests/test_functionality.sh
          ./tests/test_functionality.sh

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN_ARCH_REFLECTOR_DOCKER }}

      # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 8: Build and push the image
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.architecture }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            mschabhuettl/arch-reflector-docker:latest
            mschabhuettl/arch-reflector-docker:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/arch-reflector-docker:latest
            ghcr.io/${{ github.repository_owner }}/arch-reflector-docker:${{ github.sha }}

      # Step 9: Run Build and Runtime Tests
      - name: Run Build and Runtime Tests
        run: |
          chmod +x tests/test_build_and_run.sh
          ./tests/test_build_and_run.sh
