name: Run Security and Functionality Tests

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of tests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Run Security Tests
      - name: Run Security Tests
        run: |
          chmod +x tests/test_security.sh
          ./tests/test_security.sh

      # Step 4: Run Functionality Tests
      - name: Run Functionality Tests
        run: |
          chmod +x tests/test_functionality.sh
          ./tests/test_functionality.sh

      # Step 5: Run Build and Runtime Tests
      - name: Run Build and Runtime Tests
        run: |
          chmod +x tests/test_build_and_run.sh
          ./tests/test_build_and_run.sh
